# Generated by Django 5.2.8 on 2026-05-24 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration_weeks',
            field=models.PositiveIntegerField(blank=True, help_text='How many weeks did it take?', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Is this currently deployed and running?'),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(choices=[('SOLO', 'Solo Developer'), ('LEAD', 'Lead Developer'), ('BACKEND', 'Backend Developer'), ('FRONTEND', 'Frontend Developer'), ('FULLSTACK', 'Full Stack Developer'), ('TEAM', 'Team Member')], default='SOLO', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='swagger_url',
            field=models.URLField(blank=True, help_text='API documentation URL if applicable'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_demo_url',
            field=models.URLField(blank=True, help_text='YouTube or Loom walkthrough URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='architecture_decision',
            field=models.TextField(blank=True, help_text='One key technical decision and why you made it'),
        ),
        migrations.AlterField(
            model_name='project',
            name='problem',
            field=models.TextField(help_text='What problem does this solve?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution',
            field=models.TextField(help_text='How did you solve it?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma-separated: Django, PostgreSQL, Redis', max_length=300),
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_screenshots/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='resume.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
