# Generated by Django 5.2.8 on 2026-05-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_project_duration_weeks_project_is_live_project_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Only one profile can be featured at a time. This profile will appear first and largest on the landing page.'),
        ),
    ]
